// Static fallback checklist items used when no DB magnet has been generated yet.
export const PROBATE_FALLBACK_ITEMS = [
  { category: 'Documents to Gather', task: 'Obtain certified copies of the death certificate', description: 'You will need 8–12 copies. Required by courts, banks, insurance companies, and government agencies.', priority: 'high' },
  { category: 'Documents to Gather', task: 'Locate the original will and any codicils', description: 'Check safe deposit boxes, file cabinets, or with the deceased\'s attorney. A copy is not sufficient.', priority: 'high' },
  { category: 'Documents to Gather', task: 'Locate trusts, deeds, titles, and account statements', description: 'Gather all financial accounts, real property deeds, vehicle titles, and investment statements.', priority: 'high' },
  { category: 'People to Contact', task: 'Consult with a probate attorney', description: 'Even a brief consultation helps you understand what your state requires and avoid costly mistakes.', priority: 'high' },
  { category: 'People to Contact', task: 'Notify beneficiaries and heirs', description: 'Most states require formal notice to beneficiaries. Confirm requirements with your attorney.', priority: 'high' },
  { category: 'Property to Identify', task: 'Create a complete inventory of all assets and debts', description: 'Include real estate, vehicles, bank accounts, retirement accounts, personal property, and all known debts.', priority: 'high' },
  { category: 'Property to Identify', task: 'Identify accounts with beneficiary designations', description: 'These typically pass outside probate. Check life insurance, retirement accounts, and bank accounts.', priority: 'medium' },
  { category: 'Belongings: Sort / Keep / Sell / Donate / Discard', task: 'Work with family to decide what to keep', description: 'Allow all heirs to identify sentimental items before any sale or cleanout is scheduled.', priority: 'medium' },
  { category: 'Belongings: Sort / Keep / Sell / Donate / Discard', task: 'Document and photograph all significant items', description: 'This creates a record for the estate inventory and helps establish values for estate purposes.', priority: 'medium' },
  { category: 'When to Call an Estate Sale Company', task: 'Contact an estate sale company for significant personal property', description: 'If the home contains furniture, collectibles, jewelry, art, or tools, a licensed estate sale company can appraise, organize, and run the sale — typically taking 30–35% commission.', priority: 'high' },
  { category: 'When to Call a Realtor', task: 'Contact a probate-experienced realtor if there is real estate', description: 'A realtor familiar with probate sales understands the court approval process and can advise on timing, pricing, and preparation.', priority: 'high' },
  { category: 'When to Consider Cleanout Services', task: 'Schedule a cleanout after the estate sale', description: 'Remaining items after an estate sale can be donated, auctioned, or removed by a cleanout company. Get multiple quotes.', priority: 'medium' },
  { category: 'When to Consider an Investor Cash Offer', task: 'Get a cash offer if the home needs significant repairs', description: 'Cash buyers can close quickly and buy as-is — useful when the estate needs fast resolution or the property needs major work.', priority: 'low' },
  { category: 'Final Steps & Notes', task: 'Pay all debts, taxes, and estate expenses before distribution', description: 'Debts must be paid before assets are distributed to heirs. Consult a CPA about estate and inheritance taxes.', priority: 'high' },
  { category: 'Final Steps & Notes', task: 'File to close the estate with the probate court', description: 'Once all debts are paid and assets distributed, file a petition to formally close the estate. Confirm the process with your court or attorney.', priority: 'medium' },
];