import React, { useState } from 'react';
import { base44 } from '@/api/base44Client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Save, Eye, EyeOff, CheckCircle2, Circle, ExternalLink, Info } from 'lucide-react';

const PLATFORMS = [
  {
    key: 'facebook',
    label: 'Facebook',
    color: 'bg-blue-600',
    lightColor: 'bg-blue-50 border-blue-200',
    textColor: 'text-blue-700',
    icon: '📘',
    description: 'Post to your Facebook Page & Groups',
    fields: [
      { key: 'page_id', label: 'Page ID', placeholder: 'Your Facebook Page ID (e.g. 123456789)', hint: 'Found in your Page settings → About → Page ID' },
      { key: 'access_token', label: 'Page Access Token', placeholder: 'Long-lived Page Access Token', secret: true, hint: 'Generate at developers.facebook.com → Graph API Explorer' },
    ],
    docsUrl: 'https://developers.facebook.com/docs/pages/access-tokens',
  },
  {
    key: 'instagram',
    label: 'Instagram',
    color: 'bg-gradient-to-r from-purple-600 to-pink-500',
    lightColor: 'bg-pink-50 border-pink-200',
    textColor: 'text-pink-700',
    icon: '📸',
    description: 'Auto-post photos & reels to your Business account',
    fields: [
      { key: 'business_account_id', label: 'Instagram Business Account ID', placeholder: 'e.g. 17841400000000000', hint: 'Requires a Professional/Business Instagram account linked to a Facebook Page' },
      { key: 'access_token', label: 'Access Token', placeholder: 'Facebook User Access Token with instagram_basic scope', secret: true, hint: 'Same token as Facebook — must have instagram_content_publish permission' },
    ],
    docsUrl: 'https://developers.facebook.com/docs/instagram-api',
  },
  {
    key: 'tiktok',
    label: 'TikTok',
    color: 'bg-slate-900',
    lightColor: 'bg-slate-50 border-slate-200',
    textColor: 'text-slate-700',
    icon: '🎵',
    description: 'Publish short-form video content to TikTok',
    fields: [
      { key: 'client_key', label: 'Client Key', placeholder: 'TikTok App Client Key', hint: 'From TikTok Developer Portal → My Apps → your app' },
      { key: 'access_token', label: 'Access Token', placeholder: 'User Access Token', secret: true, hint: 'Generated via TikTok OAuth flow in your developer app' },
      { key: 'open_id', label: 'Open ID', placeholder: 'TikTok User Open ID', hint: 'Returned alongside the access token during OAuth' },
    ],
    docsUrl: 'https://developers.tiktok.com/doc/content-posting-api-get-started',
  },
  {
    key: 'youtube',
    label: 'YouTube',
    color: 'bg-red-600',
    lightColor: 'bg-red-50 border-red-200',
    textColor: 'text-red-700',
    icon: '▶️',
    description: 'Upload videos & post Community updates',
    fields: [
      { key: 'channel_id', label: 'Channel ID', placeholder: 'e.g. UCxxxxxxxxxxxxxx', hint: 'YouTube Studio → Customization → Basic Info → Channel ID' },
      { key: 'client_id', label: 'OAuth Client ID', placeholder: 'Google Cloud OAuth 2.0 Client ID', hint: 'From Google Cloud Console → APIs → Credentials' },
      { key: 'refresh_token', label: 'Refresh Token', placeholder: 'OAuth Refresh Token', secret: true, hint: 'Generated by completing Google OAuth flow with youtube.upload scope' },
    ],
    docsUrl: 'https://developers.google.com/youtube/v3/guides/uploading_a_video',
  },
  {
    key: 'pinterest',
    label: 'Pinterest',
    color: 'bg-red-700',
    lightColor: 'bg-red-50 border-red-200',
    textColor: 'text-red-700',
    icon: '📌',
    description: 'Pin estate sale photos to your boards',
    fields: [
      { key: 'board_id', label: 'Default Board ID', placeholder: 'e.g. 123456789012345', hint: 'Open your board on Pinterest and copy the ID from the URL' },
      { key: 'access_token', label: 'Access Token', placeholder: 'Pinterest App Access Token', secret: true, hint: 'From Pinterest Developer Portal → My Apps → Generate Token' },
    ],
    docsUrl: 'https://developers.pinterest.com/docs/getting-started/create-apps/',
  },
  {
    key: 'linkedin',
    label: 'LinkedIn',
    color: 'bg-blue-700',
    lightColor: 'bg-blue-50 border-blue-300',
    textColor: 'text-blue-800',
    icon: '💼',
    description: 'Share professional posts to your LinkedIn Page',
    fields: [
      { key: 'organization_id', label: 'Organization URN', placeholder: 'e.g. urn:li:organization:12345678', hint: 'From your LinkedIn Company Page URL — just the number appended to the URN' },
      { key: 'access_token', label: 'Access Token', placeholder: 'LinkedIn OAuth 2.0 Access Token', secret: true, hint: 'From LinkedIn Developer Portal → OAuth 2.0 Tools with w_member_social scope' },
    ],
    docsUrl: 'https://learn.microsoft.com/en-us/linkedin/marketing/community-management/shares/posts-api',
  },
  {
    key: 'facebook_ads',
    label: 'Facebook Ads Manager',
    color: 'bg-blue-800',
    lightColor: 'bg-blue-50 border-blue-200',
    textColor: 'text-blue-800',
    icon: '📣',
    description: 'Create & manage paid ad campaigns via the Marketing API',
    fields: [
      { key: 'ad_account_id', label: 'Ad Account ID', placeholder: 'e.g. act_123456789', hint: 'Found in Ads Manager → Account Settings. Always prefixed with "act_"' },
      { key: 'app_id', label: 'App ID', placeholder: 'Facebook App ID', hint: 'From developers.facebook.com → My Apps → your app → App ID' },
      { key: 'app_secret', label: 'App Secret', placeholder: 'Facebook App Secret', secret: true, hint: 'From developers.facebook.com → My Apps → your app → App Secret' },
      { key: 'access_token', label: 'Access Token', placeholder: 'System User or Page Access Token', secret: true, hint: 'Needs ads_management + ads_read permissions. Use a System User token for long-lived access via Business Manager → System Users' },
    ],
    docsUrl: 'https://developers.facebook.com/docs/marketing-apis/get-started',
  },
  {
    key: 'twitter',
    label: 'X (Twitter)',
    color: 'bg-slate-950',
    lightColor: 'bg-slate-50 border-slate-300',
    textColor: 'text-slate-800',
    icon: '𝕏',
    description: 'Tweet sale announcements & promotions',
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Twitter API Key (Consumer Key)', hint: 'From developer.twitter.com → Projects & Apps → your app → Keys and Tokens' },
      { key: 'api_secret', label: 'API Secret', placeholder: 'API Key Secret', secret: true, hint: 'Shown once when created; regenerate if lost' },
      { key: 'access_token', label: 'Access Token', placeholder: 'Access Token', hint: 'From Keys and Tokens → Authentication Tokens' },
      { key: 'access_token_secret', label: 'Access Token Secret', placeholder: 'Access Token Secret', secret: true, hint: 'Shown once; regenerate if lost' },
    ],
    docsUrl: 'https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/api-reference/post-tweets',
  },
];

function PlatformCard({ platform, savedData, onSave }) {
  const [fields, setFields] = useState(() => {
    const init = {};
    platform.fields.forEach(f => { init[f.key] = savedData?.[f.key] || ''; });
    return init;
  });
  const [showSecrets, setShowSecrets] = useState({});
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [showHint, setShowHint] = useState({});

  const isConnected = platform.fields.some(f => savedData?.[f.key]);

  const toggleSecret = (key) => setShowSecrets(prev => ({ ...prev, [key]: !prev[key] }));
  const toggleHint = (key) => setShowHint(prev => ({ ...prev, [key]: !prev[key] }));

  const handleSave = async () => {
    setSaving(true);
    const socialCredentials = await base44.auth.me().then(u => u.social_media_credentials || {});
    socialCredentials[platform.key] = fields;
    await base44.auth.updateMe({ social_media_credentials: socialCredentials });
    onSave(platform.key, fields);
    setSaving(false);
    setSaved(true);
    setTimeout(() => setSaved(false), 2500);
  };

  const handleDisconnect = async () => {
    if (!confirm(`Remove ${platform.label} credentials?`)) return;
    const socialCredentials = await base44.auth.me().then(u => u.social_media_credentials || {});
    delete socialCredentials[platform.key];
    await base44.auth.updateMe({ social_media_credentials: socialCredentials });
    const empty = {};
    platform.fields.forEach(f => { empty[f.key] = ''; });
    setFields(empty);
    onSave(platform.key, null);
  };

  return (
    <Card className={`border ${isConnected ? 'border-green-300' : 'border-slate-200'}`}>
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className={`w-10 h-10 rounded-xl ${platform.color} flex items-center justify-center text-white text-lg flex-shrink-0`}>
              {platform.icon}
            </div>
            <div>
              <CardTitle className="text-base">{platform.label}</CardTitle>
              <p className="text-xs text-slate-500 mt-0.5">{platform.description}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {isConnected ? (
              <Badge className="bg-green-100 text-green-700 border-green-300 gap-1">
                <CheckCircle2 className="w-3 h-3" /> Connected
              </Badge>
            ) : (
              <Badge variant="outline" className="gap-1 text-slate-500">
                <Circle className="w-3 h-3" /> Not Connected
              </Badge>
            )}
            <a href={platform.docsUrl} target="_blank" rel="noopener noreferrer" className="text-slate-400 hover:text-slate-600">
              <ExternalLink className="w-4 h-4" />
            </a>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-3">
        {platform.fields.map(field => (
          <div key={field.key}>
            <div className="flex items-center gap-1 mb-1">
              <Label className="text-xs font-medium text-slate-700">{field.label}</Label>
              <button
                type="button"
                onClick={() => toggleHint(field.key)}
                className="text-slate-400 hover:text-slate-600"
              >
                <Info className="w-3 h-3" />
              </button>
            </div>
            {showHint[field.key] && (
              <p className="text-xs text-blue-600 bg-blue-50 border border-blue-100 rounded px-2 py-1 mb-1">{field.hint}</p>
            )}
            <div className="relative">
              <Input
                type={field.secret && !showSecrets[field.key] ? 'password' : 'text'}
                value={fields[field.key]}
                onChange={e => setFields(prev => ({ ...prev, [field.key]: e.target.value }))}
                placeholder={field.placeholder}
                className="text-xs pr-8"
              />
              {field.secret && (
                <button
                  type="button"
                  onClick={() => toggleSecret(field.key)}
                  className="absolute right-2 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600"
                >
                  {showSecrets[field.key] ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                </button>
              )}
            </div>
          </div>
        ))}
        <div className="flex gap-2 pt-1">
          <Button
            size="sm"
            onClick={handleSave}
            disabled={saving}
            className={saved ? 'bg-green-600 hover:bg-green-700' : 'bg-orange-600 hover:bg-orange-700'}
          >
            {saved ? <><CheckCircle2 className="w-3 h-3 mr-1" /> Saved!</> : saving ? 'Saving…' : <><Save className="w-3 h-3 mr-1" /> Save</>}
          </Button>
          {isConnected && (
            <Button size="sm" variant="outline" onClick={handleDisconnect} className="text-red-600 hover:text-red-700 border-red-200 hover:border-red-300">
              Disconnect
            </Button>
          )}
        </div>
      </CardContent>
    </Card>
  );
}

export default function SocialMediaTab({ user }) {
  const [savedCredentials, setSavedCredentials] = useState(user?.social_media_credentials || {});

  const handleSave = (platformKey, data) => {
    setSavedCredentials(prev => {
      if (!data) {
        const updated = { ...prev };
        delete updated[platformKey];
        return updated;
      }
      return { ...prev, [platformKey]: data };
    });
  };

  const connectedCount = Object.keys(savedCredentials).filter(k =>
    PLATFORMS.find(p => p.key === k) && Object.values(savedCredentials[k] || {}).some(v => v)
  ).length;

  return (
    <div className="space-y-6">
      {/* Header info */}
      <Card className="bg-gradient-to-r from-orange-50 to-purple-50 border-orange-200">
        <CardContent className="p-5">
          <div className="flex items-start gap-4">
            <div className="text-3xl">🚀</div>
            <div className="flex-1">
              <h3 className="font-semibold text-slate-900 mb-1">Social Media Integrations</h3>
              <p className="text-sm text-slate-600">
                Connect your social media accounts so the <strong>Coaching Agent</strong> can automatically post estate sale listings, promotions, and content directly to your channels.
                All credentials are stored securely and only used for authorized posting.
              </p>
              <div className="flex items-center gap-3 mt-3">
                <Badge className="bg-orange-100 text-orange-700 border-orange-300">
                  {connectedCount} of {PLATFORMS.length} Connected
                </Badge>
                <span className="text-xs text-slate-500">Click the ℹ️ icon next to any field for setup instructions</span>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Platform Cards - 2 col grid */}
      <div className="grid md:grid-cols-2 gap-4">
        {PLATFORMS.map(platform => (
          <PlatformCard
            key={platform.key}
            platform={platform}
            savedData={savedCredentials[platform.key]}
            onSave={handleSave}
          />
        ))}
      </div>

      <p className="text-xs text-slate-400 text-center">
        🔒 All API keys and tokens are encrypted and stored securely. They are never shared or used outside of your account.
      </p>
    </div>
  );
}