import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

/**
 * Scheduled function: runs daily to send queued emails from the sequence.
 * Reads LeadActivityLog records with activity_type='follow_up' and
 * activity_notes starting with 'EMAIL_QUEUED', checks if the send date
 * has arrived, and sends the email.
 *
 * Run this on a daily schedule via automations.
 */

const FROM_EMAIL = 'EstateSalen <hello@estatesalen.com>';
const BASE_URL = 'https://www.estatesalen.com';

const DISCLAIMER = `
---
This email is for educational purposes only. EstateSalen does not provide legal, tax, or financial advice.
Unsubscribe | EstateSalen.com`;

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);

    // Fetch all queued emails
    const queuedLogs = await base44.asServiceRole.entities.LeadActivityLog.filter({
      activity_type: 'follow_up',
    }, '-created_date', 500);

    const pendingQueue = queuedLogs.filter(log =>
      log.activity_notes && log.activity_notes.startsWith('EMAIL_QUEUED')
    );

    const now = new Date();
    let sent = 0;
    let skipped = 0;
    const errors = [];

    for (const log of pendingQueue) {
      try {
        // Parse the activity_notes
        const parts = {};
        log.activity_notes.split('|').forEach(part => {
          const [k, v] = part.split(':');
          if (k && v !== undefined) parts[k.trim()] = v.trim();
        });

        const delayDays = parseInt(parts['delay_days'] || '0');
        const subject = parts['subject'] || 'An update from EstateSalen';

        // Check if enough time has passed since the log was created
        const createdAt = new Date(log.created_date);
        const sendAfter = new Date(createdAt.getTime() + delayDays * 24 * 60 * 60 * 1000);

        if (now < sendAfter) {
          skipped++;
          continue; // Not time yet
        }

        // Fetch the lead
        const leads = await base44.asServiceRole.entities.EstateTransitionLead.filter({ id: log.lead_id });
        const lead = leads[0];
        if (!lead || !lead.email) { skipped++; continue; }

        // Build a generic follow-up body referencing the subject
        // (Full content is generated by sendEstateTransitionEmailSequence)
        // For robustly queued emails, re-invoke the sequence function to get content
        const seqResult = await base44.asServiceRole.functions.invoke('sendEstateTransitionEmailSequence', {
          lead_id: log.lead_id,
          send_immediately: false,
        });

        // Actually send this specific email
        await base44.asServiceRole.integrations.Core.SendEmail({
          to: lead.email,
          subject,
          body: `Hi ${lead.first_name || 'there'},\n\nThis is a follow-up from EstateSalen regarding your estate transition.\n\nPlease visit ${BASE_URL}/estate-settlement-planner for personalized next steps.\n${DISCLAIMER}`,
        });

        // Mark this log as sent by updating activity_notes
        await base44.asServiceRole.entities.LeadActivityLog.update(log.id, {
          activity_notes: log.activity_notes.replace('EMAIL_QUEUED', 'EMAIL_SENT'),
        });

        sent++;
      } catch (err) {
        errors.push({ log_id: log.id, error: err.message });
      }
    }

    return Response.json({
      processed: pendingQueue.length,
      sent,
      skipped,
      errors: errors.length,
      error_details: errors.slice(0, 10),
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});