// Master list of all sign templates extracted from the operator's sign library
// Content will be populated later — for now just titles and categories

export const SIGN_CATEGORIES = [
  { id: 'general', name: 'General Signs', color: 'bg-blue-50 text-blue-700 border-blue-200' },
  { id: 'pricing', name: 'Pricing Signs', color: 'bg-green-50 text-green-700 border-green-200' },
  { id: 'payment', name: 'Payment Signs', color: 'bg-purple-50 text-purple-700 border-purple-200' },
  { id: 'directional', name: 'Directional Signs', color: 'bg-orange-50 text-orange-700 border-orange-200' },
  { id: 'room', name: 'Room / Area Signs', color: 'bg-cyan-50 text-cyan-700 border-cyan-200' },
  { id: 'dot-pricing', name: 'DOT Pricing Signs', color: 'bg-rose-50 text-rose-700 border-rose-200' },
  { id: 'template', name: 'Templates', color: 'bg-amber-50 text-amber-700 border-amber-200' },
];

export const SIGN_TEMPLATES = [
  // ── General Signs ──
  { id: 'garage-arrow', name: 'Garage w/ Arrow', category: 'general', content: '<div style="display:flex;align-items:center;justify-content:center;gap:32px;flex:1;width:100%;"><h1 style="font-size:120px;font-weight:900;color:#1e293b;margin:0;text-transform:uppercase;letter-spacing:4px;">GARAGE</h1><svg width="120" height="120" viewBox="0 0 120 120" style="flex-shrink:0;"><defs><marker id="arrowhead" markerWidth="10" markerHeight="7" refX="10" refY="3.5" orient="auto"><polygon points="0 0, 10 3.5, 0 7" fill="#f97316"/></marker></defs><line x1="0" y1="60" x2="100" y2="60" stroke="#f97316" stroke-width="8" marker-end="url(#arrowhead)"/></svg></div>' },
  { id: 'clothing-cherry-tree', name: 'Clothing Cherry Tree', category: 'general', content: '' },
  { id: 'deck-furn-grill', name: 'Deck Furniture & Grill', category: 'general', content: '' },
  { id: 'do-not-enter-sm-4up', name: 'Do Not Enter - Sm 4 Up', category: 'general', content: '' },
  { id: 'do-not-enter', name: 'Do Not Enter', category: 'general', content: '' },
  { id: 'facebook-instagram', name: 'Facebook and Instagram', category: 'general', content: '' },
  { id: 'facebook', name: 'Facebook', category: 'general', content: '' },
  { id: 'gate-opens-10am', name: 'Gate Opens at 10 am', category: 'general', content: '' },
  { id: 'join-email-text', name: 'Join Email or Text', category: 'general', content: '' },
  { id: 'no-large-bags', name: 'No Large Bags', category: 'general', content: '' },
  { id: 'no-parking-here', name: 'No Parking Here', category: 'general', content: '' },
  { id: 'no-public-restroom', name: 'No Public Restroom', category: 'general', content: '' },
  { id: 'no-refunds', name: 'No Refunds', category: 'general', content: '' },
  { id: 'not-for-sale-sm-4up', name: 'Not for Sale - Sm 4 Up', category: 'general', content: '' },
  { id: 'not-for-sale', name: 'Not For Sale', category: 'general', content: '' },
  { id: 'open-cabinet', name: 'Open Cabinet', category: 'general', content: '' },
  { id: 'over-10-50-perc-off', name: 'Over 10 - 50% Off', category: 'general', content: '' },
  { id: 'remove-shoes', name: 'Remove Shoes', category: 'general', content: '' },
  { id: 'sale-in-barn', name: 'Sale in Barn', category: 'general', content: '' },
  { id: 'sale-starts-10am', name: 'Sale Starts 10 am', category: 'general', content: '' },
  { id: 'sign-in-sheet', name: 'Sign in Sheet', category: 'general', content: '' },
  { id: 'single-brand-group', name: 'Single Brand Group Product', category: 'general', content: '' },
  { id: 'starting-time', name: 'Starting Time', category: 'general', content: '' },
  { id: 'vera', name: 'Vera', category: 'general', content: '' },
  { id: 'video-cameras', name: 'Video Cameras', category: 'general', content: '' },
  { id: 'video-games-cherry-tree', name: 'Video Games Cherry Tree', category: 'general', content: '' },
  { id: 'view-bid-item', name: 'View or Bid on this Item', category: 'general', content: '' },
  { id: 'washer-dryer', name: 'Washer Dryer', category: 'general', content: '' },
  { id: 'were-here-walk-in', name: "We're Here Walk In", category: 'general', content: '' },

  // ── Directional Signs ──
  { id: 'enter-here', name: 'Enter Here', category: 'directional', content: '' },
  { id: 'exit-here', name: 'Exit Here', category: 'directional', content: '' },
  { id: 'parking', name: 'Parking', category: 'directional', content: '' },

  // ── Room / Area Signs ──
  { id: 'master-bedroom', name: 'Master Bedroom', category: 'room', content: '' },
  { id: 'master-furniture', name: 'Master Furniture', category: 'room', content: '' },

  // ── Payment Signs ──
  { id: 'payment-cash-credit-zelle-venmo', name: 'Cash Credit Zelle Venmo', category: 'payment', content: '' },
  { id: 'payment-cash-only', name: 'Cash Only', category: 'payment', content: '' },
  { id: 'payment-cash-zelle-venmo', name: 'Cash Zelle Venmo', category: 'payment', content: '' },
  { id: 'payment-venmo-qr', name: 'Venmo QR Code', category: 'payment', content: '' },
  { id: 'payment-zelle-qr', name: 'Zelle QR Code', category: 'payment', content: '' },

  // ── DOT Pricing Signs ──
  { id: 'dot-pricing-day1-alt', name: 'DOT Pricing Day 1 - Alt', category: 'dot-pricing', content: '' },
  { id: 'dot-pricing-day1', name: 'DOT Pricing Day 1', category: 'dot-pricing', content: '' },
  { id: 'dot-pricing-day2', name: 'DOT Pricing Day 2', category: 'dot-pricing', content: '' },
  { id: 'pricing-dots', name: 'Pricing Dots', category: 'dot-pricing', content: '' },

  // ── Pricing Signs ──
  { id: 'pricing-sm-4up', name: 'Pricing - Sm 4 Up', category: 'pricing', content: '' },
  { id: 'pricing-sm-4up-2', name: 'Pricing - Sm 4 Up -2', category: 'pricing', content: '' },
  { id: 'pricing-sm-4up-3', name: 'Pricing - Sm 4 Up -3', category: 'pricing', content: '' },
  { id: 'pricing-sm-4up-4', name: 'Pricing - Sm 4 Up -4', category: 'pricing', content: '' },
  { id: 'pricing-sm-4up-5', name: 'Pricing - Sm 4 Up -5', category: 'pricing', content: '' },
  { id: 'pricing-sm-4up-6', name: 'Pricing - Sm 4 Up -6', category: 'pricing', content: '' },
  { id: 'pricing-sm-4up-7', name: 'Pricing - Sm 4 Up -7', category: 'pricing', content: '' },
  { id: 'pricing-sm-4up-8', name: 'Pricing - Sm 4 Up -8', category: 'pricing', content: '' },
  { id: 'pricing-sm-4up-9', name: 'Pricing - Sm 4 Up -9', category: 'pricing', content: '' },
  { id: 'pricing-4up', name: 'Pricing - 4 Up', category: 'pricing', content: '' },
  { id: 'pricing-angels', name: 'Angels', category: 'pricing', content: '' },
  { id: 'pricing-bedroom-set', name: 'Bedroom Set', category: 'pricing', content: '' },
  { id: 'pricing-books', name: 'Books', category: 'pricing', content: '' },
  { id: 'pricing-christmas-decor-2', name: 'Christmas Decor 2', category: 'pricing', content: '' },
  { id: 'pricing-christmas-decor', name: 'Christmas Decor', category: 'pricing', content: '' },
  { id: 'pricing-cleaners-detergents', name: 'Cleaners Detergents', category: 'pricing', content: '' },
  { id: 'pricing-clothing-womens-2', name: 'Clothing - Womens 2', category: 'pricing', content: '' },
  { id: 'pricing-clothing-womens', name: 'Clothing - Womens', category: 'pricing', content: '' },
  { id: 'pricing-dining-set', name: 'Dining Set', category: 'pricing', content: '' },
  { id: 'pricing-duvets-quilts', name: 'Duvets and Quilts', category: 'pricing', content: '' },
  { id: 'pricing-dvd-movie-cd', name: 'DVD Movie CD Video Games', category: 'pricing', content: '' },
  { id: 'pricing-flowers-decor', name: 'Flowers Decor', category: 'pricing', content: '' },
  { id: 'pricing-funko-pop', name: 'Funko Pop', category: 'pricing', content: '' },
  { id: 'pricing-girl-scout-tins', name: 'Girl Scout Tins', category: 'pricing', content: '' },
  { id: 'pricing-glass-cookware', name: 'Glass Cookware', category: 'pricing', content: '' },
  { id: 'pricing-hand-tools', name: 'Hand Tools', category: 'pricing', content: '' },
  { id: 'pricing-linens-sheets-towels', name: 'Linens Sheets Towels', category: 'pricing', content: '' },
  { id: 'pricing-mea', name: 'Mea', category: 'pricing', content: '' },
  { id: 'pricing-metal-frying-pots', name: 'Metal Frying Pots and Other', category: 'pricing', content: '' },
  { id: 'pricing-mugs-tea-cups', name: 'Mugs Tea Cups Plates Glasses', category: 'pricing', content: '' },
  { id: 'pricing-nailing-tools', name: 'Nailing Tools', category: 'pricing', content: '' },
  { id: 'pricing-paints-stains', name: 'Paints and Stains', category: 'pricing', content: '' },
  { id: 'pricing-partylite', name: 'Partylite', category: 'pricing', content: '' },
  { id: 'pricing-perc-off', name: 'Perc Off', category: 'pricing', content: '' },
  { id: 'pricing-planters', name: 'Planters', category: 'pricing', content: '' },
  { id: 'pricing-plants', name: 'Plants', category: 'pricing', content: '' },
  { id: 'pricing-plates', name: 'Plates', category: 'pricing', content: '' },
  { id: 'pricing-posters', name: 'Posters', category: 'pricing', content: '' },
  { id: 'pricing-power-saws', name: 'Power Saws', category: 'pricing', content: '' },
  { id: 'pricing-q-fig', name: 'Q Fig', category: 'pricing', content: '' },
  { id: 'pricing-records-albums', name: 'Records Albums', category: 'pricing', content: '' },
  { id: 'pricing-small-power-tools-batteries', name: 'Small Power Tools - Batteries', category: 'pricing', content: '' },
  { id: 'pricing-small-power-tools-corded', name: 'Small Power Tools - Corded', category: 'pricing', content: '' },
  { id: 'pricing-small-tools', name: 'Small Tools', category: 'pricing', content: '' },
  { id: 'pricing-toys-games', name: 'Toys Games', category: 'pricing', content: '' },
  { id: 'pricing-tupperware-plastic', name: 'Tupperware Plastic Storage', category: 'pricing', content: '' },
  { id: 'pricing-vtg-designer-glass', name: 'Vtg Designer Glass Cookware', category: 'pricing', content: '' },
  { id: 'pricing-weights-fitness', name: 'Weights Fitness', category: 'pricing', content: '' },
  { id: 'pricing-wire', name: 'Wire', category: 'pricing', content: '' },

  // ── Templates ──
  { id: 'template-fb-ads', name: 'Sample FB Ads', category: 'template', content: '' },
  { id: 'template-fb-marketplace', name: 'Sample FB Marketplace', category: 'template', content: '' },
  { id: 'template-sample-letter', name: 'Sample Letter', category: 'template', content: '' },
];